### ISSUE TITLE
Autoupdate keeps adding duplicated GNOME 44.1 entries every week

### ISSUE THREAD

**Issue by JamiKettunen** [brunodrugowick/notification-position-gnome-extension#12]
Just looks at [the commit history](https://github.com/brunodrugowick/notification-position-gnome-extension/commits/master), [`CHANGELOG.md`](https://github.com/brunodrugowick/notification-position-gnome-extension/blob/master/CHANGELOG.md) or [`metadata.json`](https://github.com/brunodrugowick/notification-position-gnome-extension/blob/master/src/metadata.json)

Ping @brunodrugowick

**Comment by brunodrugowick** [comment]
Hahahah, what a mess. Thanks for letting me know.
