### ISSUE TITLE
Gnome 45 not work

### ISSUE THREAD

**Issue by sagitariozod** [brunodrugowick/notification-position-gnome-extension#16]
Not word in gnome 45.

Any solution?

Tanks.

**Comment by brunodrugowick** [comment]
I heard there's a breaking change in Gnome 45 but haven't acted on it yet. I'll take a look over the weekend.

**Comment by brunodrugowick** [comment]
Which OS are you on?

**Comment by brunodrugowick** [comment]
Gnome 45 now work 😄
