### ISSUE TITLE
Is Gnome 45 supported ?

### ISSUE THREAD

**Issue by ForteDexe** [brunodrugowick/notification-position-gnome-extension#18]
Just browsing through this on Gnome extension website, look like it is miss leading right
![image](https://github.com/brunodrugowick/notification-position-gnome-extension/assets/57673412/cf89cbe0-876c-4864-b961-4dc16027c109)

**Comment by brunodrugowick** [comment]
Sorry... what?

**Comment by ForteDexe** [comment]
Sorry (a bit drunk last time), I mean I installed your extension on gnome 45, but it didnt work.
As checked on your github, it didnt support gnome 45. But on gnome extension website (the picture), written support gnome 45.
-> So maybe it is misleading there.
OR: your extension actually support gnome 45, just something wrong with my pc.

**Comment by brunodrugowick** [comment]
Nothing wrong on your side. There's support for Gnome 45 but it's currently failing and I'm investigating.

**Comment by brunodrugowick** [comment]
https://github.com/brunodrugowick/notification-position-gnome-extension/pull/17

And also #19, where I'll track this from now on.

**Comment by brunodrugowick** [comment]
Should be fixed now (a kind soul submitted a PR). I tested on Endeavour OS with Gnome 45.
