### ISSUE TITLE
Error `unexpected token: identifier` after upgrading Ubuntu 23.10 / Gnome 45

### ISSUE THREAD

**Issue by zigarn** [brunodrugowick/notification-position-gnome-extension#19]
On Gnome extensions:
![Capture d’écran du 2023-10-16 09-11-00](https://github.com/brunodrugowick/notification-position-gnome-extension/assets/175128/1196fa18-03fc-4ce4-8980-01713d01f9ba)

On [Website](https://extensions.gnome.org/extension/4105/notification-banner-position/):
![Capture d’écran du 2023-10-16 09-11-36](https://github.com/brunodrugowick/notification-position-gnome-extension/assets/175128/91067bdd-d62b-49ba-82d6-5ce3a0b085cc)

On [Extensions manager](https://github.com/mjakeman/extension-manager):
![Capture d’écran du 2023-10-16 09-10-46](https://github.com/brunodrugowick/notification-position-gnome-extension/assets/175128/9cfd4607-7ba6-4941-b3c4-49dfd07195fa)

**Comment by zigarn** [comment]
Just realized it was already raised in https://github.com/brunodrugowick/notification-position-gnome-extension/pull/17#issuecomment-1761764964.
Do you want me to close this issue or you'll use it?

**Comment by brunodrugowick** [comment]
Ah, let me use this one with all the screenshots and info to track this.

I tested myself this weekend with Endeavour OS and could see the same issue. I don't know what exactly is the problem but I know that line 9 is triggering it, which is where I try to get the current position of the banner to reset if necessary.

Maybe this changed and it's not valid anymore, idk. Will need to dig on Gnome's code I guess.
