### ISSUE TITLE
Gnome 46 support not published

### ISSUE THREAD

**Issue by zigarn** [brunodrugowick/notification-position-gnome-extension#21]
219b1cfe0a5333a589b4fe2e09a804aca66c5078 added support for Gnome 46 but https://extensions.gnome.org/extension/4105/notification-banner-position/ is still stucked at 45.
I guess publication of artifact is missing.

**Comment by brunodrugowick** [comment]
Thanks for opening this here. I pushed the artifact, it's under review now.

**Comment by brunodrugowick** [comment]
New version is active. 

![Screenshot_20240528_073724_Firefox.jpg](https://github.com/brunodrugowick/notification-position-gnome-extension/assets/7481200/50ad4f3d-0414-45a9-804c-8dfd342f6eb1)
