### ISSUE TITLE
Wrong offset

### ISSUE THREAD

**Issue by Friz64** [brunodrugowick/notification-position-gnome-extension#5]
The monitor size is always dictated by `monitors[0]`.

https://github.com/brunodrugowick/notification-position-gnome-extension/blob/8a5f57e074f517132bf85230b636bfb14b10b097/src/extension.js#L12-L13

I think what happened is that, in my monitor setup, the monitor "`monitors[0]`" is not the same width as the monitor on which the notification is being displayed.

The result:
![image](https://user-images.githubusercontent.com/20155479/141644655-eb86c1b0-b0e2-4338-84c9-4715933a96e5.png)

**Comment by brunodrugowick** [comment]
You're right, I was able to kinda reproduce changing the resolution of one of my monitors.

I wonder if there's a way to know which one is the user's primary monitor.

**Comment by Friz64** [comment]
Seems like there is a `Main.layoutManager.primaryMonitor`! https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/c3f5aa6c5c4d06acd89837119cbe380f092cae67/js/ui/layout.js

**Comment by brunodrugowick** [comment]
Nice! This works... I'll push some changes in a new version in a few.

Will also update the extensions website, so you can get an update from your settings.

**Comment by Friz64** [comment]
Awesome, i tested the latest version from https://extensions.gnome.org/extension/4105/notification-banner-position/ (version 5) and it works flawlessly! Thank you for your work, this issue can be closed
